### ISSUE TITLE
Test Plan Preparation

### ISSUE THREAD

**Issue by eozd** [bounswe/bounswe2016group6#19]
In this assignment, you will create your test plan, which will include your process and
conventions. Configurations in your Github issues, should also be documented. Process
includes, who will do what, when, how, …

Your plan must also include the user/functional test scenarios, based on your requirements and
use case and associated sequence diagrams. In particular, the content creation and search
scenarios are very important. During this process you may need feedback from your customer
in deciding on appropriate inputs and expected outputs, which you may determine and request
from your customer. In doing so, you must create specific scenarios and questions to be
answered. In other words, “Dear Customer, Please give us all the appropriate input and
expected results for this application” will obviously not be a good strategy.

In your user/functional tests, you need to describe the test, relate it to the requirements, and
clearly identify each step with appropriate data, expected results, Pass/Fail, and explanations.
You will find many useful test templates, investigate and choose a format you appreciate
(making sure that it covers the required information for testing).

**Comment by eozd** [comment]
test cases page is created. Everyone can add their own test cases.

**Comment by esraalinca** [comment]
Test cases are added.
