### ISSUE TITLE
documenting the set up process for writing code together

### ISSUE THREAD

**Issue by ahmetcj4** [bounswe/bounswe2016group6#21]
Following processes will be documented:

* which ide will be used 
* which version of java, tomcat, doxygen and other necessary programs will be used
* how to get and set up them
* how to pull the project and start to contribute the project

**Comment by eozd** [comment]
Setup document is ready and can be reached from [here](https://github.com/bounswe/bounswe2016group6/wiki/Dev-Test-Tools-Setup). All the above items are documented and versions are stated explicitly.
