### ISSUE TITLE
decide on a project management tool and apply it

### ISSUE THREAD

**Issue by ahmetcj4** [bounswe/bounswe2016group6#23]
Since it is difficult to ensure all of our team has the same version of tools we are currently or will be using, we will decide on a project management tool in near future.

Some candidates are: 
* Maven
* Gradle
* Ant

**Comment by cagirici** [comment]
Maven is a well-spread easy-to-use and comes preinstalled with EclipseEE. After discussions, it is decided that the project is now managed by Maven. Jena is added to dependency list as an example.
