### ISSUE TITLE
Creation of Activity Diagrams

### ISSUE THREAD

**Issue by cagirici** [bounswe/bounswe2016group6#7]
Activity diagrams that represents the general flow of the system should be designed and created.
All diagrams must be labeled and numbered.

**Comment by goflb** [comment]
Below are the images that will be used for the Wiki page - I am merely uploading the images via this issue.

![create topic add materials](https://cloud.githubusercontent.com/assets/8034884/14131981/35ab4814-f649-11e5-9db6-dd6b8f0e1baa.jpeg)
